### ISSUE TITLE
[dev] Add gitpod support

### ISSUE THREAD

**Issue by Merith-TK** [FiguraMC/Figura#17]
to do this, just make two files in the root of the repo
`.gitpod.yml`
```yml
image:
  file: .gitpod.Dockerfile

ports:
  - port: 25565
    onOpen: notify

vscode:
  extensions:
    - richardwillis.vscode-gradle
    - vscjava.vscode-java-pack

```
`.gitpod.Dockerfile`
```docker
FROM gitpod/workspace-base

USER gitpod

# Install Java 8 and 17
RUN sudo apt-get -q update && \
    sudo apt install -yq openjdk-8-jdk openjdk-17-jdk

# Set Java 17 as default JDK
RUN sudo update-java-alternatives --set java-1.17.0-openjdk-amd64
```
